version: '3'

services:
  app:
    build: .
    ports:
      - 3001:3000 # app
    networks:
      - broker-network
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1" # to reach localhost

networks:
  broker-network:
    name: broker-network
    driver: bridge
