GET http://localhost:3000

### Create a new asset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset1",
  "symbol": "A1",
  "price": 100
}

### List all assets
GET http://localhost:3000/assets


### Create a new wallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet1"
}

### List all wallets
GET http://localhost:3000/wallets


### Add a new asset to a wallet
POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset1",
  "shares": 10
}

### List all assets from wallet
GET http://localhost:3000/wallets/wallet1/assets


### Add a new order to wallet
POST http://localhost:3000/wallets/wallet1/orders
Content-Type: application/json

{
  "asset_id": "asset1",
  "shares": 5,
  "price": 100,
  "type": "BUY"
}

### List all orders by wallet
GET http://localhost:3000/wallets/wallet1/orders

### Execute order
POST http://localhost:3000/wallets/wallet1/orders/execute
Content-Type: application/json

{
  "order_id" : "64985b8def802d0631e6af2a", // ID of the added order
  "status": "CLOSED",
  "related_investor_id": "xxxx",
  "broker_transaction_id": "xxxx",
  "negotiated_shares": 10,
  "price": 10
}