version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000 # app
      - 5555:5555 # prisma studio
    networks:
      - broker-network
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1" # to reach localhost

  db:
    image: bitnami/mongodb:5.0.17
    networks:
      - broker-network
    environment:
      MONGODB_ADVERTISED_HOSTNAME: localhost
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_DATABASE: homebroker
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
    driver: local

networks:
  broker-network:
    name: broker-network
    driver: bridge